2021/02/16 19:51:40 [error] 1069#1069: *65 open() "/var/project/yii2/frontend/web404" failed (2: No such file or directory), client: 127.0.0.1, server: yii2, request: "GET / HTTP/1.1", host: "yii2"
2021/02/16 20:11:21 [error] 6189#6189: *1 open() "/var/project/yii2/frontend/web404" failed (2: No such file or directory), client: 127.0.0.1, server: yii2, request: "GET / HTTP/1.1", host: "yii2"
2021/02/16 20:12:31 [error] 6298#6298: *1 open() "/var/project/yii2/frontend/web404" failed (2: No such file or directory), client: 127.0.0.1, server: yii2, request: "GET / HTTP/1.1", host: "yii2"
2021/02/16 20:15:47 [error] 6547#6547: *1 FastCGI sent in stderr: "PHP message: PHP Warning:  mkdir(): Permission denied in /var/project/yii2/vendor/yiisoft/yii2/helpers/BaseFileHelper.php on line 640" while reading upstream, client: 127.0.0.1, server: yii2, request: "GET / HTTP/1.1", upstream: "fastcgi://unix:/run/php/php7.4-fpm.sock:", host: "yii2"
2021/02/16 20:15:47 [error] 6547#6547: *1 FastCGI sent in stderr: "PHP message: PHP Warning:  file_put_contents(/var/project/yii2/runtime/debug/602c0bd33796d.data): failed to open stream: No such file or directory in /var/project/yii2/vendor/yiisoft/yii2-debug/src/LogTarget.php on line 74" while reading upstream, client: 127.0.0.1, server: yii2, request: "GET / HTTP/1.1", upstream: "fastcgi://unix:/run/php/php7.4-fpm.sock:", host: "yii2"
2021/03/01 19:45:50 [error] 1202#1202: *33 FastCGI sent in stderr: "PHP message: An Error occurred while handling another error:
yii\base\InvalidRouteException: Unable to resolve the request "site/error". in /var/project/yii2/vendor/yiisoft/yii2/base/Module.php:543
Stack trace:
#0 /var/project/yii2/vendor/yiisoft/yii2/web/ErrorHandler.php(109): yii\base\Module->runAction()
#1 /var/project/yii2/vendor/yiisoft/yii2/base/ErrorHandler.php(135): yii\web\ErrorHandler->renderException()
#2 [internal function]: yii\base\ErrorHandler->handleException()
#3 {main}
Previous exception:
yii\base\InvalidRouteException: Unable to resolve the request "". in /var/project/yii2/vendor/yiisoft/yii2/base/Module.php:543
Stack trace:
#0 /var/project/yii2/vendor/yiisoft/yii2/web/Application.php(104): yii\base\Module->runAction()
#1 /var/project/yii2/vendor/yiisoft/yii2/base/Application.php(392): yii\web\Application->handleRequest()
#2 /var/project/yii2/web/index.php(12): yii\base\Application->run()
#3 {main}

Next yii\web\NotFoundHttpException: Page not found. in /var/project/yii2/vendor/" while reading upstream, client: 127.0.0.1, server: yii2, request: "GET / HTTP/1.1", upstream: "fastcgi://unix:/run/php/php7.4-fpm.sock:", host: "yii2"
2021/03/01 19:54:23 [error] 1202#1202: *37 FastCGI sent in stderr: "PHP message: An Error occurred while handling another error:
yii\base\InvalidRouteException: Unable to resolve the request "site/error". in /var/project/yii2/vendor/yiisoft/yii2/base/Module.php:543
Stack trace:
#0 /var/project/yii2/vendor/yiisoft/yii2/web/ErrorHandler.php(109): yii\base\Module->runAction()
#1 /var/project/yii2/vendor/yiisoft/yii2/base/ErrorHandler.php(135): yii\web\ErrorHandler->renderException()
#2 [internal function]: yii\base\ErrorHandler->handleException()
#3 {main}
Previous exception:
yii\base\InvalidRouteException: Unable to resolve the request "". in /var/project/yii2/vendor/yiisoft/yii2/base/Module.php:543
Stack trace:
#0 /var/project/yii2/vendor/yiisoft/yii2/web/Application.php(104): yii\base\Module->runAction()
#1 /var/project/yii2/vendor/yiisoft/yii2/base/Application.php(392): yii\web\Application->handleRequest()
#2 /var/project/yii2/web/index.php(12): yii\base\Application->run()
#3 {main}

Next yii\web\NotFoundHttpException: Page not found. in /var/project/yii2/vendor/" while reading upstream, client: 127.0.0.1, server: yii2, request: "GET / HTTP/1.1", upstream: "fastcgi://unix:/run/php/php7.4-fpm.sock:", host: "yii2"
2021/03/01 19:55:12 [error] 1202#1202: *37 FastCGI sent in stderr: "PHP message: An Error occurred while handling another error:
yii\base\InvalidRouteException: Unable to resolve the request "site/error". in /var/project/yii2/vendor/yiisoft/yii2/base/Module.php:543
Stack trace:
#0 /var/project/yii2/vendor/yiisoft/yii2/web/ErrorHandler.php(109): yii\base\Module->runAction()
#1 /var/project/yii2/vendor/yiisoft/yii2/base/ErrorHandler.php(135): yii\web\ErrorHandler->renderException()
#2 [internal function]: yii\base\ErrorHandler->handleException()
#3 {main}
Previous exception:
yii\base\InvalidRouteException: Unable to resolve the request "". in /var/project/yii2/vendor/yiisoft/yii2/base/Module.php:543
Stack trace:
#0 /var/project/yii2/vendor/yiisoft/yii2/web/Application.php(104): yii\base\Module->runAction()
#1 /var/project/yii2/vendor/yiisoft/yii2/base/Application.php(392): yii\web\Application->handleRequest()
#2 /var/project/yii2/web/index.php(12): yii\base\Application->run()
#3 {main}

Next yii\web\NotFoundHttpException: Page not found. in /var/project/yii2/vendor/" while reading upstream, client: 127.0.0.1, server: yii2, request: "GET / HTTP/1.1", upstream: "fastcgi://unix:/run/php/php7.4-fpm.sock:", host: "yii2"
2021/03/01 19:55:44 [error] 1202#1202: *37 FastCGI sent in stderr: "PHP message: An Error occurred while handling another error:
yii\base\InvalidRouteException: Unable to resolve the request "site/error". in /var/project/yii2/vendor/yiisoft/yii2/base/Module.php:543
Stack trace:
#0 /var/project/yii2/vendor/yiisoft/yii2/web/ErrorHandler.php(109): yii\base\Module->runAction()
#1 /var/project/yii2/vendor/yiisoft/yii2/base/ErrorHandler.php(135): yii\web\ErrorHandler->renderException()
#2 [internal function]: yii\base\ErrorHandler->handleException()
#3 {main}
Previous exception:
yii\base\InvalidRouteException: Unable to resolve the request "". in /var/project/yii2/vendor/yiisoft/yii2/base/Module.php:543
Stack trace:
#0 /var/project/yii2/vendor/yiisoft/yii2/web/Application.php(104): yii\base\Module->runAction()
#1 /var/project/yii2/vendor/yiisoft/yii2/base/Application.php(392): yii\web\Application->handleRequest()
#2 /var/project/yii2/web/index.php(12): yii\base\Application->run()
#3 {main}

Next yii\web\NotFoundHttpException: Page not found. in /var/project/yii2/vendor/" while reading upstream, client: 127.0.0.1, server: yii2, request: "GET / HTTP/1.1", upstream: "fastcgi://unix:/run/php/php7.4-fpm.sock:", host: "yii2"
2021/03/01 19:57:45 [error] 1202#1202: *41 FastCGI sent in stderr: "PHP message: An Error occurred while handling another error:
yii\base\InvalidRouteException: Unable to resolve the request "site/error". in /var/project/yii2/vendor/yiisoft/yii2/base/Module.php:543
Stack trace:
#0 /var/project/yii2/vendor/yiisoft/yii2/web/ErrorHandler.php(109): yii\base\Module->runAction()
#1 /var/project/yii2/vendor/yiisoft/yii2/base/ErrorHandler.php(135): yii\web\ErrorHandler->renderException()
#2 [internal function]: yii\base\ErrorHandler->handleException()
#3 {main}
Previous exception:
yii\base\InvalidRouteException: Unable to resolve the request "". in /var/project/yii2/vendor/yiisoft/yii2/base/Module.php:543
Stack trace:
#0 /var/project/yii2/vendor/yiisoft/yii2/web/Application.php(104): yii\base\Module->runAction()
#1 /var/project/yii2/vendor/yiisoft/yii2/base/Application.php(392): yii\web\Application->handleRequest()
#2 /var/project/yii2/web/index.php(12): yii\base\Application->run()
#3 {main}

Next yii\web\NotFoundHttpException: Page not found. in /var/project/yii2/vendor/" while reading upstream, client: 127.0.0.1, server: yii2, request: "GET / HTTP/1.1", upstream: "fastcgi://unix:/run/php/php7.4-fpm.sock:", host: "yii2"
2021/03/01 19:58:01 [error] 1202#1202: *41 FastCGI sent in stderr: "PHP message: An Error occurred while handling another error:
yii\base\InvalidRouteException: Unable to resolve the request "site/error". in /var/project/yii2/vendor/yiisoft/yii2/base/Module.php:543
Stack trace:
#0 /var/project/yii2/vendor/yiisoft/yii2/web/ErrorHandler.php(109): yii\base\Module->runAction()
#1 /var/project/yii2/vendor/yiisoft/yii2/base/ErrorHandler.php(135): yii\web\ErrorHandler->renderException()
#2 [internal function]: yii\base\ErrorHandler->handleException()
#3 {main}
Previous exception:
yii\base\InvalidRouteException: Unable to resolve the request "". in /var/project/yii2/vendor/yiisoft/yii2/base/Module.php:543
Stack trace:
#0 /var/project/yii2/vendor/yiisoft/yii2/web/Application.php(104): yii\base\Module->runAction()
#1 /var/project/yii2/vendor/yiisoft/yii2/base/Application.php(392): yii\web\Application->handleRequest()
#2 /var/project/yii2/web/index.php(12): yii\base\Application->run()
#3 {main}

Next yii\web\NotFoundHttpException: Page not found. in /var/project/yii2/vendor/" while reading upstream, client: 127.0.0.1, server: yii2, request: "GET / HTTP/1.1", upstream: "fastcgi://unix:/run/php/php7.4-fpm.sock:", host: "yii2"
2021/03/01 19:59:27 [error] 1202#1202: *44 FastCGI sent in stderr: "PHP message: An Error occurred while handling another error:
yii\base\InvalidRouteException: Unable to resolve the request "site/error". in /var/project/yii2/vendor/yiisoft/yii2/base/Module.php:543
Stack trace:
#0 /var/project/yii2/vendor/yiisoft/yii2/web/ErrorHandler.php(109): yii\base\Module->runAction()
#1 /var/project/yii2/vendor/yiisoft/yii2/base/ErrorHandler.php(135): yii\web\ErrorHandler->renderException()
#2 [internal function]: yii\base\ErrorHandler->handleException()
#3 {main}
Previous exception:
yii\base\InvalidRouteException: Unable to resolve the request "". in /var/project/yii2/vendor/yiisoft/yii2/base/Module.php:543
Stack trace:
#0 /var/project/yii2/vendor/yiisoft/yii2/web/Application.php(104): yii\base\Module->runAction()
#1 /var/project/yii2/vendor/yiisoft/yii2/base/Application.php(392): yii\web\Application->handleRequest()
#2 /var/project/yii2/web/index.php(12): yii\base\Application->run()
#3 {main}

Next yii\web\NotFoundHttpException: Page not found. in /var/project/yii2/vendor/" while reading upstream, client: 127.0.0.1, server: yii2, request: "GET / HTTP/1.1", upstream: "fastcgi://unix:/run/php/php7.4-fpm.sock:", host: "yii2"
2021/03/01 20:04:29 [error] 1202#1202: *46 FastCGI sent in stderr: "PHP message: An Error occurred while handling another error:
yii\base\InvalidRouteException: Unable to resolve the request "site/error". in /var/project/yii2/vendor/yiisoft/yii2/base/Module.php:543
Stack trace:
#0 /var/project/yii2/vendor/yiisoft/yii2/web/ErrorHandler.php(109): yii\base\Module->runAction()
#1 /var/project/yii2/vendor/yiisoft/yii2/base/ErrorHandler.php(135): yii\web\ErrorHandler->renderException()
#2 [internal function]: yii\base\ErrorHandler->handleException()
#3 {main}
Previous exception:
yii\base\InvalidRouteException: Unable to resolve the request "". in /var/project/yii2/vendor/yiisoft/yii2/base/Module.php:543
Stack trace:
#0 /var/project/yii2/vendor/yiisoft/yii2/web/Application.php(104): yii\base\Module->runAction()
#1 /var/project/yii2/vendor/yiisoft/yii2/base/Application.php(392): yii\web\Application->handleRequest()
#2 /var/project/yii2/web/index.php(12): yii\base\Application->run()
#3 {main}

Next yii\web\NotFoundHttpException: Page not found. in /var/project/yii2/vendor/" while reading upstream, client: 127.0.0.1, server: yii2, request: "GET / HTTP/1.1", upstream: "fastcgi://unix:/run/php/php7.4-fpm.sock:", host: "yii2"
2021/03/01 20:05:21 [error] 1202#1202: *46 FastCGI sent in stderr: "PHP message: An Error occurred while handling another error:
yii\base\InvalidRouteException: Unable to resolve the request "site/frontend/error". in /var/project/yii2/vendor/yiisoft/yii2/base/Module.php:543
Stack trace:
#0 /var/project/yii2/vendor/yiisoft/yii2/web/ErrorHandler.php(109): yii\base\Module->runAction()
#1 /var/project/yii2/vendor/yiisoft/yii2/base/ErrorHandler.php(135): yii\web\ErrorHandler->renderException()
#2 [internal function]: yii\base\ErrorHandler->handleException()
#3 {main}
Previous exception:
yii\base\InvalidRouteException: Unable to resolve the request "". in /var/project/yii2/vendor/yiisoft/yii2/base/Module.php:543
Stack trace:
#0 /var/project/yii2/vendor/yiisoft/yii2/web/Application.php(104): yii\base\Module->runAction()
#1 /var/project/yii2/vendor/yiisoft/yii2/base/Application.php(392): yii\web\Application->handleRequest()
#2 /var/project/yii2/web/index.php(12): yii\base\Application->run()
#3 {main}

Next yii\web\NotFoundHttpException: Page not found. in /var/project/yii" while reading upstream, client: 127.0.0.1, server: yii2, request: "GET / HTTP/1.1", upstream: "fastcgi://unix:/run/php/php7.4-fpm.sock:", host: "yii2"
2021/03/01 20:06:28 [error] 1202#1202: *49 FastCGI sent in stderr: "PHP message: An Error occurred while handling another error:
yii\base\InvalidRouteException: Unable to resolve the request "site/error". in /var/project/yii2/vendor/yiisoft/yii2/base/Module.php:543
Stack trace:
#0 /var/project/yii2/vendor/yiisoft/yii2/web/ErrorHandler.php(109): yii\base\Module->runAction()
#1 /var/project/yii2/vendor/yiisoft/yii2/base/ErrorHandler.php(135): yii\web\ErrorHandler->renderException()
#2 [internal function]: yii\base\ErrorHandler->handleException()
#3 {main}
Previous exception:
yii\base\InvalidRouteException: Unable to resolve the request "". in /var/project/yii2/vendor/yiisoft/yii2/base/Module.php:543
Stack trace:
#0 /var/project/yii2/vendor/yiisoft/yii2/web/Application.php(104): yii\base\Module->runAction()
#1 /var/project/yii2/vendor/yiisoft/yii2/base/Application.php(392): yii\web\Application->handleRequest()
#2 /var/project/yii2/web/index.php(12): yii\base\Application->run()
#3 {main}

Next yii\web\NotFoundHttpException: Page not found. in /var/project/yii2/vendor/" while reading upstream, client: 127.0.0.1, server: yii2, request: "GET / HTTP/1.1", upstream: "fastcgi://unix:/run/php/php7.4-fpm.sock:", host: "yii2"
2021/03/01 20:06:29 [error] 1202#1202: *49 FastCGI sent in stderr: "PHP message: An Error occurred while handling another error:
yii\base\InvalidRouteException: Unable to resolve the request "site/error". in /var/project/yii2/vendor/yiisoft/yii2/base/Module.php:543
Stack trace:
#0 /var/project/yii2/vendor/yiisoft/yii2/web/ErrorHandler.php(109): yii\base\Module->runAction()
#1 /var/project/yii2/vendor/yiisoft/yii2/base/ErrorHandler.php(135): yii\web\ErrorHandler->renderException()
#2 [internal function]: yii\base\ErrorHandler->handleException()
#3 {main}
Previous exception:
yii\base\InvalidRouteException: Unable to resolve the request "". in /var/project/yii2/vendor/yiisoft/yii2/base/Module.php:543
Stack trace:
#0 /var/project/yii2/vendor/yiisoft/yii2/web/Application.php(104): yii\base\Module->runAction()
#1 /var/project/yii2/vendor/yiisoft/yii2/base/Application.php(392): yii\web\Application->handleRequest()
#2 /var/project/yii2/web/index.php(12): yii\base\Application->run()
#3 {main}

Next yii\web\NotFoundHttpException: Page not found. in /var/project/yii2/vendor/" while reading upstream, client: 127.0.0.1, server: yii2, request: "GET / HTTP/1.1", upstream: "fastcgi://unix:/run/php/php7.4-fpm.sock:", host: "yii2"
2021/03/01 20:06:29 [error] 1202#1202: *49 FastCGI sent in stderr: "PHP message: An Error occurred while handling another error:
yii\base\InvalidRouteException: Unable to resolve the request "site/error". in /var/project/yii2/vendor/yiisoft/yii2/base/Module.php:543
Stack trace:
#0 /var/project/yii2/vendor/yiisoft/yii2/web/ErrorHandler.php(109): yii\base\Module->runAction()
#1 /var/project/yii2/vendor/yiisoft/yii2/base/ErrorHandler.php(135): yii\web\ErrorHandler->renderException()
#2 [internal function]: yii\base\ErrorHandler->handleException()
#3 {main}
Previous exception:
yii\base\InvalidRouteException: Unable to resolve the request "". in /var/project/yii2/vendor/yiisoft/yii2/base/Module.php:543
Stack trace:
#0 /var/project/yii2/vendor/yiisoft/yii2/web/Application.php(104): yii\base\Module->runAction()
#1 /var/project/yii2/vendor/yiisoft/yii2/base/Application.php(392): yii\web\Application->handleRequest()
#2 /var/project/yii2/web/index.php(12): yii\base\Application->run()
#3 {main}

Next yii\web\NotFoundHttpException: Page not found. in /var/project/yii2/vendor/" while reading upstream, client: 127.0.0.1, server: yii2, request: "GET / HTTP/1.1", upstream: "fastcgi://unix:/run/php/php7.4-fpm.sock:", host: "yii2"
2021/03/01 20:06:32 [error] 1202#1202: *49 FastCGI sent in stderr: "PHP message: An Error occurred while handling another error:
yii\base\InvalidRouteException: Unable to resolve the request "site/error". in /var/project/yii2/vendor/yiisoft/yii2/base/Module.php:543
Stack trace:
#0 /var/project/yii2/vendor/yiisoft/yii2/web/ErrorHandler.php(109): yii\base\Module->runAction()
#1 /var/project/yii2/vendor/yiisoft/yii2/base/ErrorHandler.php(135): yii\web\ErrorHandler->renderException()
#2 [internal function]: yii\base\ErrorHandler->handleException()
#3 {main}
Previous exception:
yii\base\InvalidRouteException: Unable to resolve the request "". in /var/project/yii2/vendor/yiisoft/yii2/base/Module.php:543
Stack trace:
#0 /var/project/yii2/vendor/yiisoft/yii2/web/Application.php(104): yii\base\Module->runAction()
#1 /var/project/yii2/vendor/yiisoft/yii2/base/Application.php(392): yii\web\Application->handleRequest()
#2 /var/project/yii2/web/index.php(12): yii\base\Application->run()
#3 {main}

Next yii\web\NotFoundHttpException: Page not found. in /var/project/yii2/vendor/" while reading upstream, client: 127.0.0.1, server: yii2, request: "GET / HTTP/1.1", upstream: "fastcgi://unix:/run/php/php7.4-fpm.sock:", host: "yii2"
2021/03/01 20:09:12 [error] 1202#1202: *54 FastCGI sent in stderr: "PHP message: An Error occurred while handling another error:
yii\base\InvalidRouteException: Unable to resolve the request "site/error". in /var/project/yii2/vendor/yiisoft/yii2/base/Module.php:543
Stack trace:
#0 /var/project/yii2/vendor/yiisoft/yii2/web/ErrorHandler.php(109): yii\base\Module->runAction()
#1 /var/project/yii2/vendor/yiisoft/yii2/base/ErrorHandler.php(135): yii\web\ErrorHandler->renderException()
#2 [internal function]: yii\base\ErrorHandler->handleException()
#3 {main}
Previous exception:
yii\base\InvalidRouteException: Unable to resolve the request "". in /var/project/yii2/vendor/yiisoft/yii2/base/Module.php:543
Stack trace:
#0 /var/project/yii2/vendor/yiisoft/yii2/web/Application.php(104): yii\base\Module->runAction()
#1 /var/project/yii2/vendor/yiisoft/yii2/base/Application.php(392): yii\web\Application->handleRequest()
#2 /var/project/yii2/web/index.php(12): yii\base\Application->run()
#3 {main}

Next yii\web\NotFoundHttpException: Page not found. in /var/project/yii2/vendor/" while reading upstream, client: 127.0.0.1, server: yii2, request: "GET / HTTP/1.1", upstream: "fastcgi://unix:/run/php/php7.4-fpm.sock:", host: "yii2"
2021/03/01 20:09:13 [error] 1202#1202: *54 FastCGI sent in stderr: "PHP message: An Error occurred while handling another error:
yii\base\InvalidRouteException: Unable to resolve the request "site/error". in /var/project/yii2/vendor/yiisoft/yii2/base/Module.php:543
Stack trace:
#0 /var/project/yii2/vendor/yiisoft/yii2/web/ErrorHandler.php(109): yii\base\Module->runAction()
#1 /var/project/yii2/vendor/yiisoft/yii2/base/ErrorHandler.php(135): yii\web\ErrorHandler->renderException()
#2 [internal function]: yii\base\ErrorHandler->handleException()
#3 {main}
Previous exception:
yii\base\InvalidRouteException: Unable to resolve the request "". in /var/project/yii2/vendor/yiisoft/yii2/base/Module.php:543
Stack trace:
#0 /var/project/yii2/vendor/yiisoft/yii2/web/Application.php(104): yii\base\Module->runAction()
#1 /var/project/yii2/vendor/yiisoft/yii2/base/Application.php(392): yii\web\Application->handleRequest()
#2 /var/project/yii2/web/index.php(12): yii\base\Application->run()
#3 {main}

Next yii\web\NotFoundHttpException: Page not found. in /var/project/yii2/vendor/" while reading upstream, client: 127.0.0.1, server: yii2, request: "GET / HTTP/1.1", upstream: "fastcgi://unix:/run/php/php7.4-fpm.sock:", host: "yii2"
2021/03/01 20:09:13 [error] 1202#1202: *54 FastCGI sent in stderr: "PHP message: An Error occurred while handling another error:
yii\base\InvalidRouteException: Unable to resolve the request "site/error". in /var/project/yii2/vendor/yiisoft/yii2/base/Module.php:543
Stack trace:
#0 /var/project/yii2/vendor/yiisoft/yii2/web/ErrorHandler.php(109): yii\base\Module->runAction()
#1 /var/project/yii2/vendor/yiisoft/yii2/base/ErrorHandler.php(135): yii\web\ErrorHandler->renderException()
#2 [internal function]: yii\base\ErrorHandler->handleException()
#3 {main}
Previous exception:
yii\base\InvalidRouteException: Unable to resolve the request "". in /var/project/yii2/vendor/yiisoft/yii2/base/Module.php:543
Stack trace:
#0 /var/project/yii2/vendor/yiisoft/yii2/web/Application.php(104): yii\base\Module->runAction()
#1 /var/project/yii2/vendor/yiisoft/yii2/base/Application.php(392): yii\web\Application->handleRequest()
#2 /var/project/yii2/web/index.php(12): yii\base\Application->run()
#3 {main}

Next yii\web\NotFoundHttpException: Page not found. in /var/project/yii2/vendor/" while reading upstream, client: 127.0.0.1, server: yii2, request: "GET / HTTP/1.1", upstream: "fastcgi://unix:/run/php/php7.4-fpm.sock:", host: "yii2"
2021/03/01 20:09:13 [error] 1202#1202: *54 FastCGI sent in stderr: "PHP message: An Error occurred while handling another error:
yii\base\InvalidRouteException: Unable to resolve the request "site/error". in /var/project/yii2/vendor/yiisoft/yii2/base/Module.php:543
Stack trace:
#0 /var/project/yii2/vendor/yiisoft/yii2/web/ErrorHandler.php(109): yii\base\Module->runAction()
#1 /var/project/yii2/vendor/yiisoft/yii2/base/ErrorHandler.php(135): yii\web\ErrorHandler->renderException()
#2 [internal function]: yii\base\ErrorHandler->handleException()
#3 {main}
Previous exception:
yii\base\InvalidRouteException: Unable to resolve the request "". in /var/project/yii2/vendor/yiisoft/yii2/base/Module.php:543
Stack trace:
#0 /var/project/yii2/vendor/yiisoft/yii2/web/Application.php(104): yii\base\Module->runAction()
#1 /var/project/yii2/vendor/yiisoft/yii2/base/Application.php(392): yii\web\Application->handleRequest()
#2 /var/project/yii2/web/index.php(12): yii\base\Application->run()
#3 {main}

Next yii\web\NotFoundHttpException: Page not found. in /var/project/yii2/vendor/" while reading upstream, client: 127.0.0.1, server: yii2, request: "GET / HTTP/1.1", upstream: "fastcgi://unix:/run/php/php7.4-fpm.sock:", host: "yii2"
2021/03/01 20:14:29 [error] 1202#1202: *59 FastCGI sent in stderr: "PHP message: PHP Warning:  mkdir(): Permission denied in /var/project/yii2/vendor/yiisoft/yii2/helpers/BaseFileHelper.php on line 640" while reading upstream, client: 127.0.0.1, server: yii2, request: "GET / HTTP/1.1", upstream: "fastcgi://unix:/run/php/php7.4-fpm.sock:", host: "yii2"
2021/03/01 20:14:29 [error] 1202#1202: *59 FastCGI sent in stderr: "PHP message: PHP Warning:  mkdir(): No such file or directory in /var/project/yii2/vendor/yiisoft/yii2/helpers/BaseFileHelper.php on line 640" while reading upstream, client: 127.0.0.1, server: yii2, request: "GET / HTTP/1.1", upstream: "fastcgi://unix:/run/php/php7.4-fpm.sock:", host: "yii2"
2021/03/01 20:14:29 [error] 1202#1202: *59 FastCGI sent in stderr: "PHP message: PHP Warning:  mkdir(): Permission denied in /var/project/yii2/vendor/yiisoft/yii2/helpers/BaseFileHelper.php on line 640" while reading upstream, client: 127.0.0.1, server: yii2, request: "GET / HTTP/1.1", upstream: "fastcgi://unix:/run/php/php7.4-fpm.sock:", host: "yii2"
2021/03/01 20:14:29 [error] 1202#1202: *59 FastCGI sent in stderr: "PHP message: PHP Warning:  mkdir(): No such file or directory in /var/project/yii2/vendor/yiisoft/yii2/helpers/BaseFileHelper.php on line 640" while reading upstream, client: 127.0.0.1, server: yii2, request: "GET / HTTP/1.1", upstream: "fastcgi://unix:/run/php/php7.4-fpm.sock:", host: "yii2"
2021/03/01 20:14:29 [error] 1202#1202: *59 FastCGI sent in stderr: "PHP message: PHP Warning:  file_put_contents(/var/project/yii2/frontend/runtime/debug/603d2f05159e0.data): failed to open stream: No such file or directory in /var/project/yii2/vendor/yiisoft/yii2-debug/src/LogTarget.php on line 74" while reading upstream, client: 127.0.0.1, server: yii2, request: "GET / HTTP/1.1", upstream: "fastcgi://unix:/run/php/php7.4-fpm.sock:", host: "yii2"
2021/03/01 20:15:07 [error] 1202#1202: *59 FastCGI sent in stderr: "PHP message: An Error occurred while handling another error:
yii\base\InvalidRouteException: Unable to resolve the request "site/error". in /var/project/yii2/vendor/yiisoft/yii2/base/Module.php:543
Stack trace:
#0 /var/project/yii2/vendor/yiisoft/yii2/web/ErrorHandler.php(109): yii\base\Module->runAction()
#1 /var/project/yii2/vendor/yiisoft/yii2/base/ErrorHandler.php(135): yii\web\ErrorHandler->renderException()
#2 [internal function]: yii\base\ErrorHandler->handleException()
#3 {main}
Previous exception:
yii\base\InvalidRouteException: Unable to resolve the request "". in /var/project/yii2/vendor/yiisoft/yii2/base/Module.php:543
Stack trace:
#0 /var/project/yii2/vendor/yiisoft/yii2/web/Application.php(104): yii\base\Module->runAction()
#1 /var/project/yii2/vendor/yiisoft/yii2/base/Application.php(392): yii\web\Application->handleRequest()
#2 /var/project/yii2/web/index.php(12): yii\base\Application->run()
#3 {main}

Next yii\web\NotFoundHttpException: Page not found. in /var/project/yii2/vendor/" while reading upstream, client: 127.0.0.1, server: yii2, request: "GET / HTTP/1.1", upstream: "fastcgi://unix:/run/php/php7.4-fpm.sock:", host: "yii2"
2021/03/01 20:15:11 [error] 1202#1202: *59 FastCGI sent in stderr: "PHP message: An Error occurred while handling another error:
yii\base\InvalidRouteException: Unable to resolve the request "site/error". in /var/project/yii2/vendor/yiisoft/yii2/base/Module.php:543
Stack trace:
#0 /var/project/yii2/vendor/yiisoft/yii2/web/ErrorHandler.php(109): yii\base\Module->runAction()
#1 /var/project/yii2/vendor/yiisoft/yii2/base/ErrorHandler.php(135): yii\web\ErrorHandler->renderException()
#2 [internal function]: yii\base\ErrorHandler->handleException()
#3 {main}
Previous exception:
yii\base\InvalidRouteException: Unable to resolve the request "". in /var/project/yii2/vendor/yiisoft/yii2/base/Module.php:543
Stack trace:
#0 /var/project/yii2/vendor/yiisoft/yii2/web/Application.php(104): yii\base\Module->runAction()
#1 /var/project/yii2/vendor/yiisoft/yii2/base/Application.php(392): yii\web\Application->handleRequest()
#2 /var/project/yii2/web/index.php(12): yii\base\Application->run()
#3 {main}

Next yii\web\NotFoundHttpException: Page not found. in /var/project/yii2/vendor/" while reading upstream, client: 127.0.0.1, server: yii2, request: "GET / HTTP/1.1", upstream: "fastcgi://unix:/run/php/php7.4-fpm.sock:", host: "yii2"
2021/03/01 20:15:11 [error] 1202#1202: *59 FastCGI sent in stderr: "PHP message: An Error occurred while handling another error:
yii\base\InvalidRouteException: Unable to resolve the request "site/error". in /var/project/yii2/vendor/yiisoft/yii2/base/Module.php:543
Stack trace:
#0 /var/project/yii2/vendor/yiisoft/yii2/web/ErrorHandler.php(109): yii\base\Module->runAction()
#1 /var/project/yii2/vendor/yiisoft/yii2/base/ErrorHandler.php(135): yii\web\ErrorHandler->renderException()
#2 [internal function]: yii\base\ErrorHandler->handleException()
#3 {main}
Previous exception:
yii\base\InvalidRouteException: Unable to resolve the request "". in /var/project/yii2/vendor/yiisoft/yii2/base/Module.php:543
Stack trace:
#0 /var/project/yii2/vendor/yiisoft/yii2/web/Application.php(104): yii\base\Module->runAction()
#1 /var/project/yii2/vendor/yiisoft/yii2/base/Application.php(392): yii\web\Application->handleRequest()
#2 /var/project/yii2/web/index.php(12): yii\base\Application->run()
#3 {main}

Next yii\web\NotFoundHttpException: Page not found. in /var/project/yii2/vendor/" while reading upstream, client: 127.0.0.1, server: yii2, request: "GET / HTTP/1.1", upstream: "fastcgi://unix:/run/php/php7.4-fpm.sock:", host: "yii2"
2021/03/01 20:15:12 [error] 1202#1202: *59 FastCGI sent in stderr: "PHP message: An Error occurred while handling another error:
yii\base\InvalidRouteException: Unable to resolve the request "site/error". in /var/project/yii2/vendor/yiisoft/yii2/base/Module.php:543
Stack trace:
#0 /var/project/yii2/vendor/yiisoft/yii2/web/ErrorHandler.php(109): yii\base\Module->runAction()
#1 /var/project/yii2/vendor/yiisoft/yii2/base/ErrorHandler.php(135): yii\web\ErrorHandler->renderException()
#2 [internal function]: yii\base\ErrorHandler->handleException()
#3 {main}
Previous exception:
yii\base\InvalidRouteException: Unable to resolve the request "". in /var/project/yii2/vendor/yiisoft/yii2/base/Module.php:543
Stack trace:
#0 /var/project/yii2/vendor/yiisoft/yii2/web/Application.php(104): yii\base\Module->runAction()
#1 /var/project/yii2/vendor/yiisoft/yii2/base/Application.php(392): yii\web\Application->handleRequest()
#2 /var/project/yii2/web/index.php(12): yii\base\Application->run()
#3 {main}

Next yii\web\NotFoundHttpException: Page not found. in /var/project/yii2/vendor/" while reading upstream, client: 127.0.0.1, server: yii2, request: "GET / HTTP/1.1", upstream: "fastcgi://unix:/run/php/php7.4-fpm.sock:", host: "yii2"
2021/03/01 20:15:12 [error] 1202#1202: *59 FastCGI sent in stderr: "PHP message: An Error occurred while handling another error:
yii\base\InvalidRouteException: Unable to resolve the request "site/error". in /var/project/yii2/vendor/yiisoft/yii2/base/Module.php:543
Stack trace:
#0 /var/project/yii2/vendor/yiisoft/yii2/web/ErrorHandler.php(109): yii\base\Module->runAction()
#1 /var/project/yii2/vendor/yiisoft/yii2/base/ErrorHandler.php(135): yii\web\ErrorHandler->renderException()
#2 [internal function]: yii\base\ErrorHandler->handleException()
#3 {main}
Previous exception:
yii\base\InvalidRouteException: Unable to resolve the request "". in /var/project/yii2/vendor/yiisoft/yii2/base/Module.php:543
Stack trace:
#0 /var/project/yii2/vendor/yiisoft/yii2/web/Application.php(104): yii\base\Module->runAction()
#1 /var/project/yii2/vendor/yiisoft/yii2/base/Application.php(392): yii\web\Application->handleRequest()
#2 /var/project/yii2/web/index.php(12): yii\base\Application->run()
#3 {main}

Next yii\web\NotFoundHttpException: Page not found. in /var/project/yii2/vendor/" while reading upstream, client: 127.0.0.1, server: yii2, request: "GET / HTTP/1.1", upstream: "fastcgi://unix:/run/php/php7.4-fpm.sock:", host: "yii2"
2021/03/01 20:15:13 [error] 1202#1202: *59 FastCGI sent in stderr: "PHP message: An Error occurred while handling another error:
yii\base\InvalidRouteException: Unable to resolve the request "site/error". in /var/project/yii2/vendor/yiisoft/yii2/base/Module.php:543
Stack trace:
#0 /var/project/yii2/vendor/yiisoft/yii2/web/ErrorHandler.php(109): yii\base\Module->runAction()
#1 /var/project/yii2/vendor/yiisoft/yii2/base/ErrorHandler.php(135): yii\web\ErrorHandler->renderException()
#2 [internal function]: yii\base\ErrorHandler->handleException()
#3 {main}
Previous exception:
yii\base\InvalidRouteException: Unable to resolve the request "". in /var/project/yii2/vendor/yiisoft/yii2/base/Module.php:543
Stack trace:
#0 /var/project/yii2/vendor/yiisoft/yii2/web/Application.php(104): yii\base\Module->runAction()
#1 /var/project/yii2/vendor/yiisoft/yii2/base/Application.php(392): yii\web\Application->handleRequest()
#2 /var/project/yii2/web/index.php(12): yii\base\Application->run()
#3 {main}

Next yii\web\NotFoundHttpException: Page not found. in /var/project/yii2/vendor/" while reading upstream, client: 127.0.0.1, server: yii2, request: "GET / HTTP/1.1", upstream: "fastcgi://unix:/run/php/php7.4-fpm.sock:", host: "yii2"
2021/03/01 20:15:13 [error] 1202#1202: *59 FastCGI sent in stderr: "PHP message: An Error occurred while handling another error:
yii\base\InvalidRouteException: Unable to resolve the request "site/error". in /var/project/yii2/vendor/yiisoft/yii2/base/Module.php:543
Stack trace:
#0 /var/project/yii2/vendor/yiisoft/yii2/web/ErrorHandler.php(109): yii\base\Module->runAction()
#1 /var/project/yii2/vendor/yiisoft/yii2/base/ErrorHandler.php(135): yii\web\ErrorHandler->renderException()
#2 [internal function]: yii\base\ErrorHandler->handleException()
#3 {main}
Previous exception:
yii\base\InvalidRouteException: Unable to resolve the request "". in /var/project/yii2/vendor/yiisoft/yii2/base/Module.php:543
Stack trace:
#0 /var/project/yii2/vendor/yiisoft/yii2/web/Application.php(104): yii\base\Module->runAction()
#1 /var/project/yii2/vendor/yiisoft/yii2/base/Application.php(392): yii\web\Application->handleRequest()
#2 /var/project/yii2/web/index.php(12): yii\base\Application->run()
#3 {main}

Next yii\web\NotFoundHttpException: Page not found. in /var/project/yii2/vendor/" while reading upstream, client: 127.0.0.1, server: yii2, request: "GET / HTTP/1.1", upstream: "fastcgi://unix:/run/php/php7.4-fpm.sock:", host: "yii2"
2021/03/01 20:15:14 [error] 1202#1202: *59 FastCGI sent in stderr: "PHP message: An Error occurred while handling another error:
yii\base\InvalidRouteException: Unable to resolve the request "site/error". in /var/project/yii2/vendor/yiisoft/yii2/base/Module.php:543
Stack trace:
#0 /var/project/yii2/vendor/yiisoft/yii2/web/ErrorHandler.php(109): yii\base\Module->runAction()
#1 /var/project/yii2/vendor/yiisoft/yii2/base/ErrorHandler.php(135): yii\web\ErrorHandler->renderException()
#2 [internal function]: yii\base\ErrorHandler->handleException()
#3 {main}
Previous exception:
yii\base\InvalidRouteException: Unable to resolve the request "". in /var/project/yii2/vendor/yiisoft/yii2/base/Module.php:543
Stack trace:
#0 /var/project/yii2/vendor/yiisoft/yii2/web/Application.php(104): yii\base\Module->runAction()
#1 /var/project/yii2/vendor/yiisoft/yii2/base/Application.php(392): yii\web\Application->handleRequest()
#2 /var/project/yii2/web/index.php(12): yii\base\Application->run()
#3 {main}

Next yii\web\NotFoundHttpException: Page not found. in /var/project/yii2/vendor/" while reading upstream, client: 127.0.0.1, server: yii2, request: "GET / HTTP/1.1", upstream: "fastcgi://unix:/run/php/php7.4-fpm.sock:", host: "yii2"
2021/03/05 15:14:46 [error] 5732#5732: *32 FastCGI sent in stderr: "PHP message: PHP Warning:  file_put_contents(/var/project/yii2/frontend/runtime/debug/60422ec62162c.data): failed to open stream: Permission denied in /var/project/yii2/vendor/yiisoft/yii2-debug/src/LogTarget.php on line 74" while reading upstream, client: 127.0.0.1, server: yii2, request: "POST /site/signup HTTP/1.1", upstream: "fastcgi://unix:/run/php/php7.4-fpm.sock:", host: "yii2", referrer: "http://yii2/site/signup"
